### ISSUE TITLE
A redundant semicolon at localmotion2transform.h:72

### ISSUE THREAD

**Issue by jksiezni** [georgmartius/vid.stab#11]
Hello,
I've recently created a new module to MLT framework, which uses yours latest vid.stab library, but there is a small issue, a redundant semicolon in file localmotion2transform.h at line 72.

Unfortunately, it breaks builds with g++ (my version 4.7.3):
/usr/local/include/vid.stab/localmotion2transform.h:72:41: error: expected ‘)’ before ‘;’ token
/usr/local/include/vid.stab/localmotion2transform.h:72:42: error: expected unqualified-id before ‘)’ token

It seems to affect C++ programs only, as the library itself builds without any problem.

-- 
Best regards,
Jakub Ksiezniak
